version: "3.7"

services:
  #REDIS
  redis:
    image: 'redis:alpine'
    profiles: ["credit-card", "credit-card-api"]
    env_file:
      - .env
    restart: always

  # CREDIT CARD API
  credit-card-api:
    image: "${CCAPI_IMAGE_REGISTRY_DOMAIN}/credit-card-api:latest"
    profiles: ["credit-card", "credit-card-api"]
    env_file:
      - .env
    environment:
      APP_HOST: 0.0.0.0
      APP_PORT: ${CCAPI_APP_PORT}
      NODE_ENV: ${NODE_ENV}
      LOG_LEVEL: ${LOG_LEVEL}
    build:
      context: .
      dockerfile: ./services/credit-card-api/Dockerfile.prod

  #CREDIT CARD GUI
  credit-card-gui:
    image: "${CCAPI_IMAGE_REGISTRY_DOMAIN}/credit-card-gui:latest"
    profiles: ["credit-card", "credit-card-gui"]
    env_file:
      - .env
    environment:
      REACT_APP_API_URL: ${CCGUI_API_URL}
      NODE_ENV: ${NODE_ENV}
    build:
      context: .
      dockerfile: ./apps/credit-card-gui/Dockerfile.prod

