version: "3.8"

x-aws-vpc: "vpc-0ce90a69b20a2b3c5"

services:
  redis:
      image: 'redis:alpine'
      profiles: ["credit-card"]
      volumes: 
        - cache:/data
      networks:
        - cca-network
  ccapi:
    profiles: ["credit-card"]
    environment:
        EFS_SOURCE_FOLDER: /data/src/             
        EFS_DESTINATION_FOLDER: /data/dist/              
        AWS_REGION: eu-west-1
        NODE_ENV: production
        LOG_LEVEL: error
        CCAPI_APP_HOST: 127.0.0.1
        CCAPI_APP_PORT: 8080
        CCAPI_REDIS_PORT: 6379
        CCAPI_API_PREFIX: api/v1
        CCAPI_REDIS_HOST: redis.services-cc.local
    image: 537583533687.dkr.ecr.eu-west-1.amazonaws.com/credit-card-api:latest
    x-aws-pull_policy: "arn:aws:secretsmanager:eu-west-1:537583533687:secret:services-ccs-secret"
    secrets:
      - services-ccs-secret
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5Gb'
    depends_on:
      redis:
        condition: service_started
    ports:
        - target: 8080
          x-aws-protocol: http
    volumes:
        - efs-ccapi:/data
    networks:
        - cca-network
  
  # GUI
  ccgui:
    image: 537583533687.dkr.ecr.eu-west-1.amazonaws.com/credit-card-gui:latest
    x-aws-pull_policy: "arn:aws:secretsmanager:eu-west-1:537583533687:secret:services-ccs-secret"
    secrets:
      - services-ccs-secret
    profiles: ["credit-card"]
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5Gb'
    environment:
      REACT_APP_API_URL: ccapi.services-cc.local
    ports:
      - target: 80
        x-aws-protocol: http
    depends_on:
      - ccapi
    volumes:
       - efs-ccgui:/data
    networks:
      - cca-network

networks:
  cca-network:
    driver: bridge

volumes:
  cache:
  efs-ccapi:
  efs-ccgui:

secrets:
  services-ccs-secret:
    name: "arn:aws:secretsmanager:eu-west-1:537583533687:secret:services-ccs-secret-g2m2DS"
    external: true


