name: Production - Deploy

on: 
  push:
    branches: [ main ]

jobs:
  prod-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

        # mock env file for docker compose - env vars are taken from BB env vars instead
      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: 18.13.x
          cache: npm

      - name: Prepare
        uses: actions/checkout@v3
        env:
            CCAPI_REDIS_PORT: ${CCAPI_REDIS_PORT}
            CCAPI_APP_PORT: ${CAPI_APP_PORT}
            CCAPI_NODE_ENV: ${CCAPI_NODE_ENV}
            CCAPI_LOG_LEVEL: ${CCAPI_LOG_LEVEL}
            CCGUI_API_URL: ${CCGUI_API_URL}
            CCGUI_APP_PORT: ${CCGUI_APP_PORT}
            CCAPI_ECR_URL: ${CCAPI_IMAGE_REGISTRY_URL}
            AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
        run: |
            touch .env \
            curl -L https://raw.githubusercontent.com/docker/compose-cli/main/scripts/install/install_linux.sh | sh \
            cd ../../ \
            ls -las \
            make create-deploy-context 

      - name: Lint
        run: make lint

      - name: Test
        run: make test

      - name: Build
        run: make prod-build

      - name: Push image
        run: |
          aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${CCAPI_IMAGE_REGISTRY_URL}
          make prod-push

      - name: Deploy
        run: make prod-deploy
 