name: Production - Deploy

on: 
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  prod-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    env:
      CCAPI_REDIS_PORT: ${CCAPI_REDIS_PORT}
      CCAPI_APP_PORT: ${CAPI_APP_PORT}
      CCAPI_NODE_ENV: ${CCAPI_NODE_ENV}
      CCAPI_LOG_LEVEL: ${CCAPI_LOG_LEVEL}
      CCGUI_API_URL: ${CCGUI_API_URL}
      CCGUI_APP_PORT: ${CCGUI_APP_PORT}
      CCAPI_ECR_URL: ${CCAPI_IMAGE_REGISTRY_URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: Prepare
        run: |
            touch .env \
            curl -L https://raw.githubusercontent.com/docker/compose-cli/main/scripts/install/install_linux.sh | sh \
            ls -las \
        #make create-deploy-context 

      - name: Lint
        run: make lint

      - name: Test
        run: make test

      - name: Build
        run: make prod-build

      - name: Push image
        run: |
          aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${CCAPI_IMAGE_REGISTRY_URL}
          make prod-push

      - name: Deploy
        run: make prod-deploy
 